### ISSUE TITLE
hashCode and equals in model package

### ISSUE THREAD

**Issue by jendap** [querydsl/codegen#12]
Is there a reason for hashCode and equals methods in model package to be implemented and yet not using all the fields in the classes?

Would it not be better to either remove them or regenerate them with comparing/hashing all the fields?

It breaks for example scala case class code generation in querydsl. I'm going to work around it there. But it should be fixed here.

**Comment by mdmoss** [comment]
I've just encountered the same issue, using Querydsl to generate Scala case classes. I'll make a PR there for an actual fix, but I've found that this becomes an issue when mapping over a Set[Parameter] to produce a Set[Property]. The resulting set only contains one Property of each type, because of the hashCode collisions. 

Specifically, the issue occurs in [ScalaBeanSerializer](https://github.com/querydsl/querydsl/blob/9eebd846ced67d5bdbe4bded2280a21495836f6c/querydsl-scala/src/main/scala/com/querydsl/scala/ScalaBeanSerializer.scala#L139)

(And apologies for bumping a dead thread!)
